In [1]:
import numpy as np

In [7]:
np.random.rand(3, 1, 3)

array([[[0.53559278, 0.5056602 , 0.62470431]],

       [[0.08851938, 0.09592468, 0.93205167]],

       [[0.33306251, 0.93072922, 0.89364593]]])

In [5]:
help(np.random.rand)

Help on method rand in module numpy.random:

rand(*args) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)

    Random values in a given shape.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.

    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.

    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.

    See Also
    --------
    random

    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.1402247

In [9]:
np.random.randn(3, 1, 3)

array([[[-0.73803396,  0.96147095,  1.39834183]],

       [[ 0.59061894, -0.45503415,  1.54019018]],

       [[-0.76550949, -0.2072839 ,  0.97188946]]])

In [10]:
help(np.random.randn)

Help on method randn in module numpy.random:

randn(*args) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)

    Return a sample (or samples) from the "standard normal" distribution.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distributi

In [11]:
np.random.standard_normal((3,2,4))

array([[[-1.51226904e+00, -8.20251567e-01, -1.40354743e+00,
          6.16476791e-01],
        [ 1.26929833e+00, -1.76024607e+00,  1.40720973e+00,
          2.07239176e+00]],

       [[ 4.77654855e-01, -1.98516894e+00,  8.13429425e-02,
         -5.90565154e-01],
        [ 6.95650533e-01,  4.14057363e-01, -1.88877378e-01,
          1.87743979e+00]],

       [[ 1.68808296e+00,  5.87019923e-01, -1.59953757e-01,
         -5.43511170e-01],
        [ 1.09917488e-03, -3.77875642e-01, -8.78170973e-01,
         -1.84009195e-01]]])

In [12]:
help(np.random.standard_normal)

Help on method standard_normal in module numpy.random:

standard_normal(size=None) method of numpy.random.mtrand.RandomState instance
    standard_normal(size=None)

    Draw samples from a standard Normal distribution (mean=0, stdev=1).

    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.

    Returns
    -------
    out : float or ndarray
        A floating-point array of shape ``size`` of drawn samples, or a
        single sample if ``size`` was not specified.

    See Also
    --------
    normal :
        Equivalent function with additional ``loc`` and ``scale`` arguments
    